### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [krakenjs/belter#9]
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by M-krishna** [comment]
Hi @mstuart I'd like to work on this.

**Comment by mstuart** [comment]
Hi @M-krishna, you'll need to contribute it to DefinitelyTyped. Similar to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48454

**Comment by M-krishna** [comment]
Okay @mstuart

**Comment by mstuart** [comment]
Hi @M-krishna, did you take this up? If not, wanted to leave it open for others. Thanks for your other contributions so far :D

**Comment by M-krishna** [comment]
Hi @mstuart, sorry caught up with other things. I haven't taken this yet. I'll unassign it.

**Comment by mstuart** [comment]
Np! Thanks @M-krishna

**Comment by SlyBouhafs** [comment]
Hi @mstuart, i will take up on this if there's no one assigned to it!

**Comment by SlyBouhafs** [comment]
@mstuart i sent a PR on the Definitelytyped repo for the belter package, can you review it?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49219

I will push more definition after that one gets review so i that i know i am on the right track.

**Comment by songz** [comment]
In @SlyBouhafs 's PR to DefinitelyTyped, it has a label `Author is owner`. Would it more make sense for @mstuart to be owner?

**Comment by mstuart** [comment]
Thanks @SlyBouhafs!
